### ISSUE TITLE
Top关键字 某些分类点击会显示 这里空空如也

### ISSUE THREAD

**Issue by AlexScofield** [dotnet9/Dotnet9#7]
网站右侧 Top关键字 板块 显示的分类后面带有数字 点击某些分类会显示: 这里空空如也.
![5e509223c54828ed79f13854ae1d21d](https://github.com/dotnet9/Dotnet9/assets/31263773/f280b7bf-aa74-40ac-be50-9d56c0059252)

**Comment by dotnet9** [comment]
这是正常的，用户搜索的关键词在站点没有对应的文章，这里网站可以优化下，比如不展示没有搜索结果的关键字，站长后面也会搜罗高频搜索的相关文章，谢谢提issue

**Comment by dotnet9** [comment]
没有搜索内容的关键字已经不显示了，多谢提醒
