### ISSUE TITLE
能否增加一个加密聊天室

### ISSUE THREAD

**Issue by TheDZ0104** [dotnet9/Dotnet9#9]
1.客户端自己生成rsa公钥和私钥
2.客户端可以通知服务端创建一个聊天室，也可以加入一个已知名字的聊天室
3.用户可以得到同一聊天室其它用户的公钥
4.用户在聊天室发送消息时，用聊天室内所有用户的公钥加密该消息，并通知服务端将加密的消息转发给对应的用户（该操作在客户端完成）

*服务端只实现聊天室的建立与信息的转发

**Comment by dotnet9** [comment]
你这用法可就广了，搞不好要出事，哈哈，这个不搞哈
